version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
