name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    - name: lint
      run: npm run lint
    - name: build
      run: npm run build
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        dangerous-clean-slate: true
        local-dir: ./dist/wolfautokereskedes/
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        protocol: ${{ secrets.FTP_PROTOCOL }}
        server: ${{ secrets.FTP_SERVER }}
        server-dir: ${{ secrets.FTP_SERVER_DIR }}
        username: ${{ secrets.FTP_USERNAME }}
